env:
  browser: true
  commonjs: true
  es6: true
  jest: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  arrow-parens: [error, as-needed]
  no-confusing-arrow: 0
  object-curly-spacing: [error, never]
  no-console: off
  max-len: [warn, {code: 80}]
  no-nested-ternary: off
  indent: [error, 2, ignoredNodes: [ConditionalExpression]]
